# Site Settings
title: M.I
email: gerard.boxo@estudiantat.upc.edu
description: >-
  This blog is dedicated to discussing Mechanistic Interpretability
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gboxo.github.io" # the base hostname & protocol for your site

# Author
author:
  name: "Gerard Box√≥"
  bio: "Researcher in AI Safety & AIxBio. MSc in Bioinformatics."
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/gerard-boxo-183598275/?locale=es"
    - label: "Twitter"
      url: "https://x.com/GerardBoxo_"
    - label: "GitHub"
      url: "https://github.com/gboxo"
    - label: "CV"
      url: "/assets/CV%20Gerard.pdf"

# Navigation
locale: "en-US"

# Build Settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

include:
  - logs-www
  - aixbio-hackathon
