# Site Settings
title: M.I
email: gerard.boxo@estudiantat.upc.edu
description: >-
  This blog is dedicated to discussing Mechanistic Interpretability
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gboxo.github.io" # the base hostname & protocol for your site

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
# theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Author / Sidebar
author:
  name: "Gerard Box√≥"
  avatar: "/assets/images/profile_picture.jpg"
  bio: "MSc graduate in Bioinformatics. Exploring Mechanistic Interpretability."
  location: "Barcelona"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/gerard-boxo-183598275/?locale=es"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/GerardBoxo_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gboxo"

# Navigation
# Make sure _data/navigation.yml exists
locale: "en-US"

# Build Settings
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-remote-theme

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

include:
  - logs-www
